# Generated by Django 3.2 on 2022-08-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multipage_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('multipagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multipage_form.multipagemodel')),
                ('nome_completo', models.CharField(blank=True, max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=15, verbose_name='Celular')),
                ('presencial', models.BooleanField(default=False, verbose_name='Trabalhar Presencialmente')),
                ('hibrido', models.BooleanField(default=False, verbose_name='Trabalhar Modelo Híbrido')),
                ('meio_periodo', models.BooleanField(default=False, verbose_name='Trabalhar Meio Período')),
                ('possui_pc', models.BooleanField(default=False, verbose_name='Possui Computador?')),
                ('possui_smartphone', models.BooleanField(default=False, verbose_name='Possui Smartphone?')),
                ('experiencia_profissional', models.BooleanField(default=False, verbose_name='Experiencia Profissional?')),
                ('trabalha_atualmente', models.BooleanField(default=False, verbose_name='Trabalha Atualmente?')),
                ('tudo_pronto', models.BooleanField(default=False, verbose_name='Tudo pronto?')),
            ],
            bases=('multipage_form.multipagemodel',),
        ),
    ]
