# Generated by Django 3.2 on 2022-08-19 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
