# Generated by Django 3.2 on 2022-08-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_jobapplication_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
    ]
