# Generated by Django 3.2 on 2022-08-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_jobapplication_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='elementor',
            field=models.BooleanField(default=False, verbose_name='Elementor'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ensino_medio_tecnico',
            field=models.BooleanField(default=False, verbose_name='Ensino Medio Técnico?'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='escola',
            field=models.CharField(blank=True, max_length=100, verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='formacao_cursos',
            field=models.TextField(blank=True, verbose_name='Formação e Cursos'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='nivel_profissional',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nível Profissional'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='nocode_lowcode',
            field=models.BooleanField(default=False, verbose_name='Nocode / Low Code'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='nocode_lowcode_tecnologias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tecnologias Nocode / Low Code'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='partnership',
            field=models.BooleanField(default=False, verbose_name='Partnership?'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tempo_trabalhado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tempo Trabalhado'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='wordpress',
            field=models.BooleanField(default=False, verbose_name='WordPress'),
        ),
    ]
