# Generated by Django 3.2 on 2022-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_auto_20220819_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='duvida',
            field=models.BooleanField(default=False, verbose_name='Dúvida?'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='importancia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qual a coisa mais importante da sua vida?'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='indicacao',
            field=models.BooleanField(default=False, verbose_name='Indicacao?'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='modelo_contratacao',
            field=models.CharField(blank=True, max_length=30, verbose_name='Modelo de Contratção'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='qual_duvida',
            field=models.TextField(blank=True, verbose_name='Qual a dúvida?'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='qual_sugestao',
            field=models.TextField(blank=True, verbose_name='Qual a sugestão?'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='quem_indicou',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quem indicou?'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sugestao',
            field=models.BooleanField(default=False, verbose_name='Sugestão?'),
        ),
    ]
