# Generated by Django 3.2 on 2022-08-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_auto_20220820_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='possui_empresa',
            field=models.BooleanField(default=False, verbose_name='Você possui empresa aberta?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='modelo_contratacao',
            field=models.CharField(blank=True, max_length=30, verbose_name='Modelo de Contratação'),
        ),
    ]
