# Generated by Django 3.2 on 2022-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0007_auto_20220820_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='backend',
            field=models.CharField(blank=True, max_length=30, verbose_name='Backend'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='frontend',
            field=models.CharField(blank=True, max_length=30, verbose_name='Frontend'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='produtos_e_tecnologias',
            field=models.CharField(blank=True, max_length=30, verbose_name='Produtos e Tecnologias'),
        ),
    ]
