# Generated by Django 3.2 on 2022-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0008_auto_20220820_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='curriculos/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='backend',
            field=models.CharField(blank=True, max_length=100, verbose_name='Backend'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='frontend',
            field=models.CharField(blank=True, max_length=100, verbose_name='Frontend'),
        ),
    ]
