# Generated by Django 3.2 on 2022-08-20 21:49

from django.db import migrations, models
import job_application.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0009_auto_20220820_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='partnership',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='curriculo',
            field=models.FileField(blank=True, upload_to=job_application.models.get_file_path, verbose_name='Anexe seu currículo aqui'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='duvida',
            field=models.BooleanField(default=False, verbose_name='Você tem alguma dúvida?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='elementor',
            field=models.BooleanField(default=False, verbose_name='Você conhece Elementor?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ensino_medio_tecnico',
            field=models.BooleanField(default=False, verbose_name='Você já concluiu o ensino médio técnico?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='escola',
            field=models.CharField(blank=True, max_length=100, verbose_name='Escola em que estuda/estudou'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='exame',
            field=models.BooleanField(default=False, verbose_name='Você aceita realizar um teste?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experiencia_profissional',
            field=models.BooleanField(default=False, verbose_name='Você possui experiência profissional?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='formacao_cursos',
            field=models.TextField(blank=True, verbose_name='Você possui alguma outra formação ou cursos?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='hibrido',
            field=models.BooleanField(default=False, verbose_name='Você aceita trabalhar no modelo híbrido (home office / escritório)?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='importancia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qual é a coisa MAIS IMPORTANTE da sua vida?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='indicacao',
            field=models.BooleanField(default=False, verbose_name='Você foi indicado por alguém?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ingles',
            field=models.BooleanField(default=False, verbose_name='Possui conhecimento de inglês?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='meio_periodo',
            field=models.BooleanField(default=False, verbose_name='Você aceita trabalhar meio período?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='modelo_contratacao',
            field=models.CharField(blank=True, max_length=30, verbose_name='Qual modelo de contratação você prefere ser contratado?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='nivel_profissional',
            field=models.CharField(blank=True, max_length=30, verbose_name='Qual nível profissional você se considera?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='nocode_lowcode',
            field=models.BooleanField(default=False, verbose_name='Você conhece NOCODE / LOWCODE?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='nocode_lowcode_tecnologias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quais tecnologias você conhece?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='possui_pc',
            field=models.BooleanField(default=False, verbose_name='Você possui Computador?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='possui_smartphone',
            field=models.BooleanField(default=False, verbose_name='Você possui Smartphone?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='presencial',
            field=models.BooleanField(default=False, verbose_name='Você aceita trabalhar presencialmente em nosso escritório?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='produtos_e_tecnologias',
            field=models.CharField(blank=True, max_length=30, verbose_name='Área de Desenvolvimento'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='qual_duvida',
            field=models.TextField(blank=True, verbose_name='Qual é a sua dúvida?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='qual_sugestao',
            field=models.TextField(blank=True, verbose_name='Qual é a sua sugestão?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='quem_indicou',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quem te indicou?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='sugestao',
            field=models.BooleanField(default=False, verbose_name='Você tem alguma sugestão?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='tempo_trabalhado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quanto tempo trabalhou em uma empresa?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='trabalha_atualmente',
            field=models.BooleanField(default=False, verbose_name='Você trabalha atualmente?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='wordpress',
            field=models.BooleanField(default=False, verbose_name='Você conhece WordPress?'),
        ),
    ]
